#include "Panels/ComponentGeneratorPanel.h"
#if !defined(TNX_ENABLE_EDITOR)
#error "ComponentGeneratorPanel.cpp requires TNX_ENABLE_EDITOR"
#endif

#include "EditorState.h"
#include "EngineConfig.h"
#include "Logger.h"
#include "ScriptRegistry.h"
#include "TnxStyle.h"
#include "TnxWidgets.h"
#include "imgui.h"

#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Static lookup tables
// ---------------------------------------------------------------------------

static const char* FieldTypeNames[] = {
	"float", "int32_t", "uint32_t", "bool", "Fixed32",
};
static constexpr int NumFieldTypes = 5;

static const char* TierMacros[] = {
	"TNX_TEMPORAL_FIELDS",
	"TNX_VOLATILE_FIELDS",
	"TNX_REGISTER_FIELDS",
};
static const char* TierNames[] = { "Temporal", "Volatile", "Cold" };
static constexpr int NumTiers  = 3;

static const char* GroupNames[] = { "Render", "Physics", "Logic", "Dual" };
static constexpr int NumGroups  = 4;

// ScriptFieldType and SystemID ordinals match the index arrays above.
static const ScriptFieldType TypeIndexToScript[] = {
	ScriptFieldType::Float, ScriptFieldType::Int32, ScriptFieldType::UInt32,
	ScriptFieldType::Bool,  ScriptFieldType::Fixed32,
};
static const SystemID GroupIndexToSysID[] = {
	SystemID::Render, SystemID::Physics, SystemID::Logic, SystemID::Dual,
};
static const CacheTier TierIndexToCacheTier[] = {
	CacheTier::Temporal, CacheTier::Volatile, CacheTier::Volatile, // Cold → Volatile for script
};

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

void ComponentGeneratorPanel::RegenerateCode()
{
	GeneratedCode.clear();

	if (CompName[0] == '\0')
	{
		GeneratedCode = "// Enter a component name above to generate code.";
		return;
	}

	bool isCold = (TierIndex == 2);

	std::string out;
	out += "#pragma once\n";
	out += "#include \"FieldProxy.h\"\n";
	out += "#include \"SchemaValidation.h\"\n";
	out += "\n";
	out += "// Auto-generated by Trinyx Component Generator — edit with care.\n";
	out += std::string("// Tier:  ") + TierNames[TierIndex] + "\n";
	if (!isCold)
		out += std::string("// Group: ") + GroupNames[GroupIndex] + "\n";
	out += "\n";

	out += TierMacros[TierIndex];
	out += "(";
	out += CompName;
	if (!isCold)
	{
		out += ", SystemGroup::";
		out += GroupNames[GroupIndex];
	}
	for (const auto& f : Fields)
	{
		if (f.Name[0] == '\0') continue;
		out += ", ";
		out += f.Name;
	}
	out += ");\n";

	if (bReplicated && TierIndex == 0)
		out += "TNX_NET_REPLICATED(" + std::string(CompName) + ");\n";

	out += "\n";

	out += "struct ";
	out += CompName;
	out += "\n{\n";

	for (const auto& f : Fields)
	{
		if (f.Name[0] == '\0') continue;
		out += "    FieldProxy<";
		out += FieldTypeNames[f.TypeIndex];
		out += "> ";
		out += f.Name;
		out += ";\n";
	}

	out += "\n    static void DefineFields()\n    {\n";
	for (const auto& f : Fields)
	{
		if (f.Name[0] == '\0') continue;
		out += "        Bind(&";
		out += CompName;
		out += "::";
		out += f.Name;
		out += ");\n";
	}
	out += "    }\n";
	out += "};\n";

	GeneratedCode = std::move(out);
}

bool ComponentGeneratorPanel::ExportToFile()
{
	if (OutputPath[0] == '\0')
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Set an output path before exporting.");
		bStatusError = true;
		return false;
	}
	if (CompName[0] == '\0')
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Enter a component name before exporting.");
		bStatusError = true;
		return false;
	}

	try
	{
		std::filesystem::create_directories(std::filesystem::path(OutputPath).parent_path());
	}
	catch (const std::exception& ex)
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Failed to create output directory: %s", ex.what());
		bStatusError = true;
		LOG_ENG_ERROR_F("[ComponentGenerator] Failed to create output directory: %s", ex.what());
		return false;
	}

	std::ofstream file(OutputPath);
	if (!file.is_open())
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Failed to open: %s", OutputPath);
		bStatusError = true;
		return false;
	}

	file << GeneratedCode;
	{
		const std::string s = std::string("Exported: ") + OutputPath;
		strncpy(StatusMessage, s.c_str(), sizeof(StatusMessage) - 1);
		StatusMessage[sizeof(StatusMessage) - 1] = '\0';
		LOG_ENG_INFO(s.c_str());
	}
	bStatusError = false;
	LOG_ENG_INFO_F("[ComponentGenerator] Exported '%s'", CompName);
	return true;
}

void ComponentGeneratorPanel::RegisterAsScript()
{
	if (CompName[0] == '\0')
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Enter a component name before registering.");
		bStatusError = true;
		return;
	}

	SystemID  sysID = (TierIndex < 2) ? GroupIndexToSysID[GroupIndex] : SystemID::None;
	CacheTier tier  = TierIndexToCacheTier[TierIndex];

	std::vector<ScriptFieldType> types;
	std::vector<const char*>     names;
	for (const auto& f : Fields)
	{
		if (f.Name[0] == '\0') continue;
		types.push_back(TypeIndexToScript[f.TypeIndex]);
		names.push_back(f.Name);
	}

	bool breakingChange = false;
	ComponentTypeID id  = ScriptRegistry::Get().RegisterOrUpdate(
		CompName, sysID, tier,
		types.data(), names.data(), static_cast<uint8_t>(types.size()),
		&breakingChange);

	if (breakingChange)
	{
		snprintf(StatusMessage, sizeof(StatusMessage),
			"[S] Breaking change on '%s' — fields removed or reordered. "
			"Stop PIE to re-register.", CompName);
		bStatusError = true;
	}
	else if (id == 0)
	{
		snprintf(StatusMessage, sizeof(StatusMessage), "Failed to register '%s'.", CompName);
		bStatusError = true;
	}
	else
	{
		snprintf(StatusMessage, sizeof(StatusMessage),
			"[S] '%s' live (TypeID %u, %u fields) — AoS storage, no SIMD, no rollback. "
			"Export .h when stable.",
			CompName, id, static_cast<unsigned>(types.size()));
		bStatusError = false;
	}
}

// ---------------------------------------------------------------------------
// Draw
// ---------------------------------------------------------------------------

void ComponentGeneratorPanel::Draw(EditorState& state)
{
	if (!ImGui::Begin(Title, &bVisible)) { ImGui::End(); return; }
	TnxWidgets::PanelHeader(nullptr, "Component Generator");
	ImGui::SetCursorPosY(ImGui::GetCursorPosY() + 6);
	ImGui::SetCursorPosX(ImGui::GetCursorPosX() + 8);

	bool changed = false;

	// --- Component name ---
	ImGui::Text("Component Name:");
	ImGui::SameLine();
	ImGui::SetNextItemWidth(200.0f);
	if (ImGui::InputText("##CompName", CompName, sizeof(CompName)))
	{
		changed = true;
		if (state.ConfigPtr && state.ConfigPtr->ProjectDir[0] != '\0' && OutputPath[0] == '\0')
		{
			std::string suggested = std::string(state.ConfigPtr->ProjectDir)
				+ "/src/Runtime/Components/Public/" + CompName + ".h";
			snprintf(OutputPath, sizeof(OutputPath), "%s", suggested.c_str());
		}
	}

	// --- Storage tier ---
	ImGui::Text("Storage Tier:  ");
	ImGui::SameLine();
	ImGui::SetNextItemWidth(120.0f);
	if (ImGui::Combo("##Tier", &TierIndex, TierNames, NumTiers)) changed = true;

	if (TierIndex < 2)
	{
		ImGui::Text("System Group: ");
		ImGui::SameLine();
		ImGui::SetNextItemWidth(120.0f);
		if (ImGui::Combo("##Group", &GroupIndex, GroupNames, NumGroups)) changed = true;
	}

	{
		ImGui::PushStyleColor(ImGuiCol_Text, TierIndex == 0 ? TnxStyle::Color::Fg : TnxStyle::Color::FgDim);
		if (ImGui::Checkbox("Replicated (net)##rep", &bReplicated))
		{
			if (TierIndex != 0) bReplicated = false;
			changed = true;
		}
		ImGui::PopStyleColor();
		if (TierIndex != 0)
		{
			ImGui::SameLine(0, 6);
			ImGui::PushStyleColor(ImGuiCol_Text, TnxStyle::Color::FgDim);
			ImGui::TextUnformatted("(Temporal only)");
			ImGui::PopStyleColor();
		}
	}

	// --- Field list ---
	ImGui::Separator();
	ImGui::Text("Fields");
	ImGui::SameLine();
	if (ImGui::SmallButton("+##AddField"))
	{
		Fields.push_back({});
		changed = true;
	}
	ImGui::SameLine();
	ImGui::TextDisabled("(FieldProxy<T> — registered in DefineFields)");

	for (int i = 0; i < static_cast<int>(Fields.size()); i++)
	{
		auto& f = Fields[static_cast<size_t>(i)];
		ImGui::PushID(i);

		ImGui::SetNextItemWidth(160.0f);
		if (ImGui::InputText("##FName", f.Name, sizeof(f.Name))) changed = true;
		ImGui::SameLine();
		ImGui::SetNextItemWidth(100.0f);
		if (ImGui::Combo("##FType", &f.TypeIndex, FieldTypeNames, NumFieldTypes)) changed = true;
		ImGui::SameLine();
		if (ImGui::SmallButton("x"))
		{
			Fields.erase(Fields.begin() + i);
			changed = true;
			ImGui::PopID();
			break;
		}

		ImGui::PopID();
	}

	// --- Actions ---
	ImGui::Separator();

	// Export .h (compile-time path)
	ImGui::Text("Output Path:");
	ImGui::SetNextItemWidth(-90.0f);
	ImGui::InputText("##OutPath", OutputPath, sizeof(OutputPath));
	ImGui::SameLine();
	if (ImGui::Button("Export .h##Exp", ImVec2(80.0f, 0.0f)))
	{
		RegenerateCode();
		ExportToFile();
	}

	// Register as ScriptComponent (runtime path — no recompile)
	ImGui::SetCursorPosY(ImGui::GetCursorPosY() + 2);
	if (ImGui::Button("Register Script [S]##Reg", ImVec2(-1.0f, 0.0f)))
		RegisterAsScript();

	if (StatusMessage[0] != '\0')
	{
		ImVec4 col = bStatusError ? ImVec4(1.0f, 0.35f, 0.35f, 1.0f) : ImVec4(0.35f, 1.0f, 0.35f, 1.0f);
		ImGui::TextColored(col, "%s", StatusMessage);
	}

	// --- Generated code preview ---
	ImGui::Separator();
	ImGui::Text("Generated Code:");

	if (changed) RegenerateCode();

	ImGui::BeginChild("##CodePreview", ImVec2(0.0f, 0.0f), ImGuiChildFlags_None,
					  ImGuiWindowFlags_HorizontalScrollbar);
	ImGui::TextUnformatted(GeneratedCode.c_str());
	ImGui::EndChild();

	ImGui::End();
}
